package md0

import (
	"html"
	"strings"
)

// runtimeStatusCSS contains only live-viewer chrome. The document itself is
// styled by documentCSS in document_style.go, which is shared by open,
// render, and snapshot output.
const runtimeStatusCSS = `
.md0-viewer-controls{position:fixed;top:16px;right:16px;z-index:60;font-family:var(--md0-font-sans);font-size:13px}.md0-settings-toggle{display:grid;place-items:center;width:40px;height:40px;padding:0;border:1px solid color-mix(in srgb,var(--line) 90%,transparent);border-radius:12px;background:color-mix(in srgb,var(--paper) 94%,transparent);color:var(--ink);box-shadow:0 8px 28px rgba(0,0,0,.08);backdrop-filter:blur(14px);font:700 13px/1 var(--md0-font-sans);cursor:pointer}.md0-settings-toggle:hover{background:var(--surface)}.md0-settings-toggle:focus-visible,.md0-settings-panel button:focus-visible{outline:2px solid var(--focus);outline-offset:2px}.md0-settings-panel{position:absolute;right:0;top:48px;width:328px;padding:16px;border:1px solid color-mix(in srgb,var(--line) 90%,transparent);border-radius:15px;background:color-mix(in srgb,var(--paper) 97%,transparent);color:var(--ink);box-shadow:0 20px 60px rgba(0,0,0,.18);backdrop-filter:blur(22px)}.md0-settings-panel[hidden]{display:none}.md0-settings-head{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:14px}.md0-settings-heading{font-size:14px;font-weight:700;letter-spacing:-.01em}.md0-settings-subtitle{color:var(--muted);font-size:11px;margin-top:2px}.md0-settings-close{border:0;background:transparent;color:var(--muted);font:20px/1 var(--md0-font-sans);cursor:pointer;padding:2px 4px}.md0-preference{margin:12px 0}.md0-preference-label{margin-bottom:6px;color:var(--muted);font:700 10px/1 var(--md0-font-sans);text-transform:uppercase;letter-spacing:.06em}.md0-segmented{display:grid;grid-auto-flow:column;grid-auto-columns:1fr;padding:3px;border-radius:11px;background:var(--surface);gap:2px}.md0-segmented button{border:0;border-radius:8px;padding:7px 8px;background:transparent;color:var(--muted);font:600 12px/1 var(--md0-font-sans);cursor:pointer}.md0-segmented button:hover{color:var(--ink)}.md0-segmented button.active{background:var(--paper);color:var(--ink);box-shadow:0 1px 2px rgba(0,0,0,.08),0 0 0 1px color-mix(in srgb,var(--line) 85%,transparent)}.md0-settings-separator{height:1px;margin:14px 0 10px;background:var(--line)}.md0-settings-actions{display:grid;gap:2px}.md0-settings-actions button{display:flex;align-items:center;justify-content:space-between;width:100%;border:0;border-radius:9px;padding:9px 10px;background:transparent;color:var(--ink);text-align:left;font:600 12px/1.2 var(--md0-font-sans);cursor:pointer}.md0-settings-actions button:hover{background:var(--surface)}.md0-settings-meta{color:var(--muted);font-weight:500}.md0-settings-reset{color:var(--muted)!important}.md0-status{position:fixed;right:16px;bottom:16px;z-index:70;max-width:min(560px,calc(100vw - 32px));padding:10px 12px;border:1px solid var(--red);border-radius:10px;background:var(--field);color:var(--red);box-shadow:0 16px 42px rgba(0,0,0,.18);font:13px/1.4 var(--md0-font-mono);white-space:pre-wrap}.md0-status[hidden]{display:none}
@media(max-width:640px){.md0-viewer-controls{top:10px;right:10px}.md0-settings-panel{position:fixed;left:12px;right:12px;top:60px;width:auto}}
`

const runtimeStatusJS = `
const md0PreferencesKey='md0:preferences:v1';
const md0PreferenceDefaults={theme:'system',font:'serif',density:'compact',textSize:'default',width:'normal'};
const md0PreferenceAttributes={theme:'md0Theme',font:'md0Font',density:'md0Density',textSize:'md0TextSize',width:'md0Width'};
function md0RuntimeToken(){const meta=document.querySelector('meta[name="md0-runtime-token"]');return meta?meta.content:''}
function md0SourceRevision(){const meta=document.querySelector('meta[name="md0-source-revision"]');return meta?meta.content:''}
function md0InputValues(){const values={};document.querySelectorAll('[data-md0-input]').forEach(el=>{values[el.name]=el.type==='checkbox'?String(el.checked):el.value});return values}
function md0StoredPreferences(){try{const value=JSON.parse(localStorage.getItem(md0PreferencesKey)||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
function md0ApplyPreferences(preferences){const root=document.documentElement;for(const [name,attr] of Object.entries(md0PreferenceAttributes)){const value=preferences[name]||md0PreferenceDefaults[name];if(name==='theme'&&value==='system'){delete root.dataset[attr]}else if(value===md0PreferenceDefaults[name]){delete root.dataset[attr]}else{root.dataset[attr]=value}}document.querySelectorAll('[data-md0-preference]').forEach(group=>{const name=group.dataset.md0Preference;const value=preferences[name]||md0PreferenceDefaults[name];group.querySelectorAll('[data-md0-value]').forEach(button=>button.classList.toggle('active',button.dataset.md0Value===value))})}
function md0LoadPreferences(){const preferences={...md0PreferenceDefaults,...md0StoredPreferences()};md0ApplyPreferences(preferences);return preferences}
function md0SavePreference(name,value){const preferences={...md0PreferenceDefaults,...md0StoredPreferences(),[name]:value};try{localStorage.setItem(md0PreferencesKey,JSON.stringify(preferences))}catch{}md0ApplyPreferences(preferences)}
function md0ResetPreferences(){try{localStorage.removeItem(md0PreferencesKey)}catch{}md0ApplyPreferences(md0PreferenceDefaults)}
function md0SetSettingsOpen(open){const panel=document.getElementById('md0-settings-panel');const toggle=document.getElementById('md0-settings-toggle');panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));if(open){const first=panel.querySelector('button');if(first)first.focus()}}
function md0EnhanceInputs(root=document){root.querySelectorAll('.md0-input').forEach(label=>{if(label.dataset.md0Enhanced==='true')return;const input=label.querySelector('[data-md0-input]');const typeLabel=label.querySelector('small');if(!input||!typeLabel)return;const type=typeLabel.textContent.trim().toLowerCase();if(type==='boolean'||type==='bool'){const shell=document.createElement('span');shell.className='md0-switch-shell';input.before(shell);shell.appendChild(input);const visual=document.createElement('span');visual.className='md0-switch-visual';visual.setAttribute('aria-hidden','true');shell.appendChild(visual);label.dataset.md0Enhanced='true';return}const control=document.createElement('span');control.className='md0-control';input.before(control);control.appendChild(input);typeLabel.classList.add('md0-unit');if(type==='percent'){typeLabel.textContent='%';typeLabel.classList.add('percent')}control.appendChild(typeLabel);if(input.type==='number'){const stepper=document.createElement('span');stepper.className='md0-stepper';stepper.setAttribute('aria-label','Value controls');for(const direction of [1,-1]){const button=document.createElement('button');button.type='button';button.className='md0-step';button.dataset.md0Step=String(direction);button.dataset.md0Target=input.id;button.setAttribute('aria-label',(direction>0?'Increase ':'Decrease ')+(input.name||'value'));button.textContent=direction>0?'↑':'↓';stepper.appendChild(button)}control.appendChild(stepper)}label.dataset.md0Enhanced='true'})}
function md0StepInput(button,event){const input=document.getElementById(button.dataset.md0Target);if(!input)return;let base=1;if(input.step&&input.step!=='any'){const parsed=Number(input.step);if(Number.isFinite(parsed)&&parsed>0)base=parsed}let multiplier=1;if(event&&event.shiftKey)multiplier=10;else if(event&&event.altKey)multiplier=.1;const direction=Number(button.dataset.md0Step)||1;const current=Number(input.value);const next=(Number.isFinite(current)?current:0)+(direction*base*multiplier);input.value=String(next);input.dispatchEvent(new Event('input',{bubbles:true}))}
let md0StepDelay;let md0StepRepeat;function md0StopStepRepeat(){clearTimeout(md0StepDelay);clearInterval(md0StepRepeat);md0StepDelay=undefined;md0StepRepeat=undefined}
function md0SetRuntimeError(message,inputName){const status=document.getElementById('md0-status');status.textContent=message;status.hidden=false;document.querySelectorAll('[data-md0-input]').forEach(el=>{if(inputName&&el.name===inputName){el.setAttribute('aria-invalid','true')}else{el.removeAttribute('aria-invalid')}})}
function md0ClearRuntimeError(){const status=document.getElementById('md0-status');status.textContent='';status.hidden=true;document.querySelectorAll('[data-md0-input]').forEach(el=>el.removeAttribute('aria-invalid'))}
async function md0Download(endpoint,filename){let r;try{r=await fetch(endpoint,{method:'POST',headers:{'x-md0-token':md0RuntimeToken()}})}catch(err){md0SetRuntimeError('md0 runtime unavailable: '+err.message,'');return}if(!r.ok){let message='md0 could not export this document';try{const payload=await r.json();message=payload.error||message}catch{}md0SetRuntimeError(message,'');return}const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);md0ClearRuntimeError()}
md0LoadPreferences();md0EnhanceInputs();
document.querySelectorAll('[data-md0-preference] [data-md0-value]').forEach(button=>button.addEventListener('click',()=>md0SavePreference(button.closest('[data-md0-preference]').dataset.md0Preference,button.dataset.md0Value)));
document.getElementById('md0-settings-reset').addEventListener('click',md0ResetPreferences);
document.getElementById('md0-settings-toggle').addEventListener('click',()=>md0SetSettingsOpen(document.getElementById('md0-settings-panel').hidden));
document.getElementById('md0-settings-close').addEventListener('click',()=>md0SetSettingsOpen(false));
document.addEventListener('keydown',event=>{if(event.key==='Escape')md0SetSettingsOpen(false)});
document.addEventListener('click',event=>{const step=event.target.closest('[data-md0-step]');if(step){md0StepInput(step,event);return}const controls=document.querySelector('.md0-viewer-controls');if(controls&&!controls.contains(event.target)&&!document.getElementById('md0-settings-panel').hidden)md0SetSettingsOpen(false)});
document.addEventListener('pointerdown',event=>{const step=event.target.closest('[data-md0-step]');if(!step)return;md0StopStepRepeat();md0StepDelay=setTimeout(()=>{md0StepRepeat=setInterval(()=>md0StepInput(step,event),80)},420)});
document.addEventListener('pointerup',md0StopStepRepeat);document.addEventListener('pointercancel',md0StopStepRepeat);
document.getElementById('md0-export-snapshot').addEventListener('click',()=>md0Download('/snapshot','document.snapshot.json'));
document.getElementById('md0-export-markdown').addEventListener('click',()=>md0Download('/markdown','document.md'));
let md0SourceProblem=false;
async function md0CheckSource(){let r;try{r=await fetch('/source-status',{headers:{'x-md0-token':md0RuntimeToken()}})}catch{return}if(!r.ok)return;let payload;try{payload=await r.json()}catch{return}if(payload.error){md0SourceProblem=true;md0SetRuntimeError(payload.error,'');return}if(payload.revision&&payload.revision!==md0SourceRevision()){if(typeof md0BeforeSourceReload==='function'&&md0BeforeSourceReload(payload.revision)===false)return;location.reload();return}if(md0SourceProblem){md0SourceProblem=false;md0ClearRuntimeError()}}
setInterval(md0CheckSource,700);
md0SendLatest=async function(){const values=md0InputValues();let r;try{r=await fetch('/render',{method:'POST',headers:{'content-type':'application/json','x-md0-token':md0RuntimeToken()},body:JSON.stringify(values)})}catch(err){md0SetRuntimeError('md0 runtime unavailable: '+err.message,'');return}let payload;try{payload=await r.json()}catch{md0SetRuntimeError('md0 runtime returned an invalid response','');return}if(!r.ok){md0SetRuntimeError(payload.error||'md0 could not evaluate this document',payload.input||'');return}md0ClearRuntimeError();for(const patch of payload.patches){const node=document.getElementById(patch.dom_id);if(!node){console.warn('md0 patch target missing',patch.node);continue}node.outerHTML=patch.html}md0EnhanceInputs()}
`

func renderInteractiveRuntimePage(title, fragment, token string) string {
	return renderInteractiveRuntimePageRevision(title, fragment, token, "")
}

func renderInteractiveRuntimePageRevision(title, fragment, token, revision string) string {
	page := RenderInteractivePage(title, fragment)
	page = strings.Replace(page, `</head>`, `<meta name="md0-runtime-token" content="`+html.EscapeString(token)+`"><meta name="md0-source-revision" content="`+html.EscapeString(revision)+`"><style>`+runtimeStatusCSS+`</style></head>`, 1)
	controls := `<div class="md0-viewer-controls"><button id="md0-settings-toggle" class="md0-settings-toggle" type="button" aria-expanded="false" aria-controls="md0-settings-panel" title="Viewer settings">Aa</button><section id="md0-settings-panel" class="md0-settings-panel" aria-label="Viewer settings" hidden><div class="md0-settings-head"><div><div class="md0-settings-heading">Viewer</div><div class="md0-settings-subtitle">Local presentation preferences</div></div><button id="md0-settings-close" class="md0-settings-close" type="button" aria-label="Close settings">×</button></div><div class="md0-preference" data-md0-preference="theme"><div class="md0-preference-label">Theme</div><div class="md0-segmented"><button type="button" data-md0-value="system">System</button><button type="button" data-md0-value="light">Light</button><button type="button" data-md0-value="dark">Dark</button></div></div><div class="md0-preference" data-md0-preference="font"><div class="md0-preference-label">Typography</div><div class="md0-segmented"><button type="button" data-md0-value="serif">Serif</button><button type="button" data-md0-value="sans">Sans</button><button type="button" data-md0-value="mono">Mono</button></div></div><div class="md0-preference" data-md0-preference="density"><div class="md0-preference-label">Density</div><div class="md0-segmented"><button type="button" data-md0-value="compact">Compact</button><button type="button" data-md0-value="comfortable">Comfort</button></div></div><div class="md0-preference" data-md0-preference="textSize"><div class="md0-preference-label">Text size</div><div class="md0-segmented"><button type="button" data-md0-value="small">Small</button><button type="button" data-md0-value="default">Default</button><button type="button" data-md0-value="large">Large</button></div></div><div class="md0-preference" data-md0-preference="width"><div class="md0-preference-label">Page width</div><div class="md0-segmented"><button type="button" data-md0-value="narrow">Narrow</button><button type="button" data-md0-value="normal">Normal</button><button type="button" data-md0-value="wide">Wide</button></div></div><div class="md0-settings-separator"></div><div class="md0-settings-actions"><button id="md0-edit-source" type="button" hidden><span>Edit source</span><span class="md0-settings-meta">⌘E</span></button><button id="md0-export-snapshot" type="button"><span>Export snapshot</span><span class="md0-settings-meta">JSON</span></button><button id="md0-export-markdown" type="button"><span>Save values to Markdown</span><span class="md0-settings-meta">.md</span></button><button id="md0-settings-reset" class="md0-settings-reset" type="button"><span>Reset viewer settings</span><span class="md0-settings-meta">↺</span></button></div></section></div>`
	page = strings.Replace(page, `<body>`, `<body>`+controls+`<aside id="md0-status" class="md0-status" role="status" aria-live="polite" hidden></aside>`, 1)
	page = strings.Replace(page, `</body>`, `<script>`+runtimeStatusJS+`</script></body>`, 1)
	return page
}
