package md0

import (
	"html"
	"strings"
)

const runtimeStatusCSS = `
:root{--md0-font-serif:Charter,"Iowan Old Style","Palatino Linotype",Palatino,"Book Antiqua",Georgia,serif;--md0-font-sans:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--md0-font-mono:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace;--md0-document-font:var(--md0-font-serif);--md0-font-size:17px;--md0-measure:760px;--md0-row-y:8px;--paper:#fff;--card:#fff;--ink:#171717;--muted:#666;--line:#d8d8d8;--green:#246b3e;--red:#9b2f2f;--focus:#245a9b;--chart-0:#151515;--chart-1:#4d4d4d;--chart-2:#7a7a7a;--chart-3:#a3a3a3;color-scheme:light}
:root[data-md0-theme="light"]{--paper:#fff;--card:#fff;--ink:#171717;--muted:#666;--line:#d8d8d8;--green:#246b3e;--red:#9b2f2f;--focus:#245a9b;--chart-0:#151515;--chart-1:#4d4d4d;--chart-2:#7a7a7a;--chart-3:#a3a3a3;color-scheme:light}
:root[data-md0-theme="dark"]{--paper:#101114;--card:#101114;--ink:#efefec;--muted:#a5a5a0;--line:#34363c;--green:#7fca99;--red:#ff9393;--focus:#a7c7ff;--chart-0:#f0f0ec;--chart-1:#b7b7b0;--chart-2:#868680;--chart-3:#5f5f5b;color-scheme:dark}
@media(prefers-color-scheme:dark){:root:not([data-md0-theme="light"]):not([data-md0-theme="dark"]){--paper:#101114;--card:#101114;--ink:#efefec;--muted:#a5a5a0;--line:#34363c;--green:#7fca99;--red:#ff9393;--focus:#a7c7ff;--chart-0:#f0f0ec;--chart-1:#b7b7b0;--chart-2:#868680;--chart-3:#5f5f5b;color-scheme:dark}}
:root[data-md0-font="sans"]{--md0-document-font:var(--md0-font-sans)}:root[data-md0-font="mono"]{--md0-document-font:var(--md0-font-mono)}
:root[data-md0-density="comfortable"]{--md0-row-y:13px}:root[data-md0-text-size="small"]{--md0-font-size:15px}:root[data-md0-text-size="large"]{--md0-font-size:19px}:root[data-md0-width="narrow"]{--md0-measure:640px}:root[data-md0-width="wide"]{--md0-measure:980px}
body{background:var(--paper);color:var(--ink);font-family:var(--md0-document-font);font-size:var(--md0-font-size);line-height:1.58;transition:background-color .12s ease,color .12s ease}#md0-document{max-width:var(--md0-measure);margin:42px auto;padding:0 24px 64px}.md0-doc h1,.md0-doc h2,.md0-doc h3{font-family:var(--md0-document-font);letter-spacing:-.015em}.md0-doc h1{font-size:2.35rem;line-height:1.08;margin:0 0 14px;padding-bottom:10px;border-bottom:1px solid var(--line)}.md0-doc h2{font-size:1.55rem;line-height:1.2;margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--line)}.md0-doc p{margin:.65em 0}.md0-doc code,.md0-chart-title,.md0-table-title{font-family:var(--md0-font-mono)}
.md0-input{display:grid;grid-template-columns:minmax(150px,1fr) minmax(130px,220px) 76px;gap:12px;align-items:center;margin:0;padding:var(--md0-row-y) 0;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;box-shadow:none}.md0-input:first-of-type{border-top:1px solid var(--line)}.md0-input:focus-within{border-color:var(--ink);box-shadow:none}.md0-input input{width:100%;padding:6px 8px;border:1px solid var(--line);border-radius:2px;background:var(--paper);color:var(--ink);font:inherit}.md0-input input[type=checkbox]{width:18px;height:18px;accent-color:var(--ink)}.md0-input input:focus-visible{outline:2px solid var(--focus);outline-offset:1px;border-color:var(--focus)}.md0-input small{color:var(--muted);font-family:var(--md0-font-mono);font-size:.76em}
.md0-show{margin:12px 0;padding:7px 10px;border:0;border-left:2px solid var(--line);border-radius:0;background:transparent}.md0-assert{margin:16px 0;padding:8px 12px;border:0;border-left:2px solid;border-radius:0;background:transparent}.md0-assert.pass{background:transparent;border-color:var(--green);color:var(--green)}.md0-assert.fail{background:transparent;border-color:var(--red);color:var(--red)}.md0-assert-title{font-family:var(--md0-font-sans);font-weight:700;text-transform:uppercase;letter-spacing:.06em;font-size:.68rem}.md0-assert code{display:block;margin-top:3px;color:inherit}.md0-assert-message p{margin:.4rem 0 0}
.md0-chart,.md0-table{margin:22px 0;padding:0;border:0;border-radius:0;background:transparent;box-shadow:none}.md0-chart-title,.md0-table-title{font-size:.72rem;color:var(--muted);margin:0 0 8px}.md0-chart svg{display:block;width:100%;height:auto}.md0-chart .axis{stroke:var(--line);stroke-width:1}.md0-chart .zero-axis{stroke:var(--muted)}.md0-chart .bar-0{fill:var(--chart-0)}.md0-chart .bar-1{fill:var(--chart-1)}.md0-chart .bar-2{fill:var(--chart-2)}.md0-chart .bar-3{fill:var(--chart-3)}.md0-chart .bar.negative{opacity:.75}.md0-chart text{font-family:var(--md0-font-mono);fill:var(--muted);font-size:14px}.md0-chart .value{fill:var(--ink);font-weight:600}.md0-table-scroll{overflow-x:auto}.md0-table table{width:100%;border-collapse:collapse;border-top:1px solid var(--ink);border-bottom:1px solid var(--ink)}.md0-table th,.md0-table td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line);white-space:nowrap}.md0-table th{font-family:var(--md0-font-sans);font-weight:650;color:var(--ink);font-size:.78rem}.md0-table tbody tr:last-child td{border-bottom:0}pre{overflow:auto;padding:12px;border:1px solid var(--line);border-radius:0;background:transparent}pre code{white-space:pre}code{font-size:.9em}strong{font-weight:700}
.md0-viewer-controls{position:fixed;top:14px;right:14px;z-index:60;font-family:var(--md0-font-sans)}.md0-settings-toggle{width:34px;height:30px;padding:0;border:1px solid var(--line);border-radius:2px;background:var(--paper);color:var(--ink);font:600 12px/1 var(--md0-font-sans);cursor:pointer}.md0-settings-toggle:hover{border-color:var(--muted)}.md0-settings-toggle:focus-visible,.md0-settings-panel button:focus-visible,.md0-settings-panel select:focus-visible{outline:2px solid var(--focus);outline-offset:2px}.md0-settings-panel{position:absolute;right:0;top:38px;width:258px;padding:12px;border:1px solid var(--line);border-radius:3px;background:var(--paper);color:var(--ink);box-shadow:0 12px 32px rgba(0,0,0,.14)}.md0-settings-panel[hidden]{display:none}.md0-settings-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.md0-settings-head strong{font-size:12px;letter-spacing:.04em}.md0-settings-close{border:0;background:transparent;color:var(--muted);font-size:18px;line-height:1;cursor:pointer}.md0-preference{display:grid;grid-template-columns:1fr 112px;gap:10px;align-items:center;padding:5px 0;font-size:12px}.md0-preference select{width:100%;padding:4px 6px;border:1px solid var(--line);border-radius:2px;background:var(--paper);color:var(--ink);font:12px/1.3 var(--md0-font-sans)}.md0-settings-separator{height:1px;margin:8px 0;background:var(--line)}.md0-settings-actions{display:grid;gap:5px}.md0-settings-actions button{padding:6px 8px;border:1px solid var(--line);border-radius:2px;background:var(--paper);color:var(--ink);text-align:left;font:12px/1.25 var(--md0-font-sans);cursor:pointer}.md0-settings-actions button:hover{border-color:var(--muted)}.md0-settings-reset{color:var(--muted)!important}.md0-status{position:fixed;right:14px;bottom:14px;z-index:70;max-width:min(560px,calc(100vw - 28px));padding:9px 11px;border:1px solid var(--red);border-radius:2px;background:var(--paper);color:var(--red);box-shadow:0 10px 28px rgba(0,0,0,.14);font:13px/1.4 var(--md0-font-mono);white-space:pre-wrap}.md0-status[hidden]{display:none}.md0-input input[aria-invalid="true"]{border-color:var(--red);outline:2px solid color-mix(in srgb,var(--red) 24%,transparent)}
@media(max-width:640px){#md0-document{margin:28px auto;padding:0 18px 48px}.md0-doc h1{font-size:2rem}.md0-input{grid-template-columns:1fr 110px;gap:8px}.md0-input small{grid-column:2}.md0-viewer-controls{top:8px;right:8px}.md0-settings-panel{position:fixed;left:12px;right:12px;top:46px;width:auto}}
`

const runtimeStatusJS = `
const md0PreferencesKey='md0:preferences:v1';
const md0PreferenceDefaults={theme:'system',font:'serif',density:'compact',textSize:'default',width:'normal'};
const md0PreferenceAttributes={theme:'md0Theme',font:'md0Font',density:'md0Density',textSize:'md0TextSize',width:'md0Width'};
function md0RuntimeToken(){const meta=document.querySelector('meta[name="md0-runtime-token"]');return meta?meta.content:''}
function md0SourceRevision(){const meta=document.querySelector('meta[name="md0-source-revision"]');return meta?meta.content:''}
function md0InputValues(){const values={};document.querySelectorAll('[data-md0-input]').forEach(el=>{values[el.name]=el.type==='checkbox'?String(el.checked):el.value});return values}
function md0StoredPreferences(){try{const value=JSON.parse(localStorage.getItem(md0PreferencesKey)||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
function md0ApplyPreferences(preferences){const root=document.documentElement;for(const [name,attr] of Object.entries(md0PreferenceAttributes)){const value=preferences[name]||md0PreferenceDefaults[name];if(name==='theme'&&value==='system'){delete root.dataset[attr]}else if(value===md0PreferenceDefaults[name]){delete root.dataset[attr]}else{root.dataset[attr]=value}}document.querySelectorAll('[data-md0-preference]').forEach(select=>{select.value=preferences[select.dataset.md0Preference]||md0PreferenceDefaults[select.dataset.md0Preference]})}
function md0LoadPreferences(){const preferences={...md0PreferenceDefaults,...md0StoredPreferences()};md0ApplyPreferences(preferences);return preferences}
function md0SavePreference(name,value){const preferences={...md0PreferenceDefaults,...md0StoredPreferences(),[name]:value};try{localStorage.setItem(md0PreferencesKey,JSON.stringify(preferences))}catch{}md0ApplyPreferences(preferences)}
function md0ResetPreferences(){try{localStorage.removeItem(md0PreferencesKey)}catch{}md0ApplyPreferences(md0PreferenceDefaults)}
function md0SetSettingsOpen(open){const panel=document.getElementById('md0-settings-panel');const toggle=document.getElementById('md0-settings-toggle');panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));if(open){const first=panel.querySelector('select,button');if(first)first.focus()}}
function md0SetRuntimeError(message,inputName){const status=document.getElementById('md0-status');status.textContent=message;status.hidden=false;document.querySelectorAll('[data-md0-input]').forEach(el=>{if(inputName&&el.name===inputName){el.setAttribute('aria-invalid','true')}else{el.removeAttribute('aria-invalid')}})}
function md0ClearRuntimeError(){const status=document.getElementById('md0-status');status.textContent='';status.hidden=true;document.querySelectorAll('[data-md0-input]').forEach(el=>el.removeAttribute('aria-invalid'))}
async function md0Download(endpoint,filename){let r;try{r=await fetch(endpoint,{method:'POST',headers:{'x-md0-token':md0RuntimeToken()}})}catch(err){md0SetRuntimeError('md0 runtime unavailable: '+err.message,'');return}if(!r.ok){let message='md0 could not export this document';try{const payload=await r.json();message=payload.error||message}catch{}md0SetRuntimeError(message,'');return}const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);md0ClearRuntimeError()}
md0LoadPreferences();
document.querySelectorAll('[data-md0-preference]').forEach(select=>select.addEventListener('change',()=>md0SavePreference(select.dataset.md0Preference,select.value)));
document.getElementById('md0-settings-reset').addEventListener('click',md0ResetPreferences);
document.getElementById('md0-settings-toggle').addEventListener('click',()=>md0SetSettingsOpen(document.getElementById('md0-settings-panel').hidden));
document.getElementById('md0-settings-close').addEventListener('click',()=>md0SetSettingsOpen(false));
document.addEventListener('keydown',event=>{if(event.key==='Escape')md0SetSettingsOpen(false)});
document.addEventListener('click',event=>{const controls=document.querySelector('.md0-viewer-controls');if(!controls.contains(event.target)&&!document.getElementById('md0-settings-panel').hidden)md0SetSettingsOpen(false)});
document.getElementById('md0-export-snapshot').addEventListener('click',()=>md0Download('/snapshot','document.snapshot.json'));
document.getElementById('md0-export-markdown').addEventListener('click',()=>md0Download('/markdown','document.md'));
let md0SourceProblem=false;
async function md0CheckSource(){let r;try{r=await fetch('/source-status',{headers:{'x-md0-token':md0RuntimeToken()}})}catch{return}if(!r.ok)return;let payload;try{payload=await r.json()}catch{return}if(payload.error){md0SourceProblem=true;md0SetRuntimeError(payload.error,'');return}if(payload.revision&&payload.revision!==md0SourceRevision()){location.reload();return}if(md0SourceProblem){md0SourceProblem=false;md0ClearRuntimeError()}}
setInterval(md0CheckSource,700);
md0SendLatest=async function(){const values=md0InputValues();let r;try{r=await fetch('/render',{method:'POST',headers:{'content-type':'application/json','x-md0-token':md0RuntimeToken()},body:JSON.stringify(values)})}catch(err){md0SetRuntimeError('md0 runtime unavailable: '+err.message,'');return}let payload;try{payload=await r.json()}catch{md0SetRuntimeError('md0 runtime returned an invalid response','');return}if(!r.ok){md0SetRuntimeError(payload.error||'md0 could not evaluate this document',payload.input||'');return}md0ClearRuntimeError();for(const patch of payload.patches){const node=document.getElementById(patch.dom_id);if(!node){console.warn('md0 patch target missing',patch.node);continue}node.outerHTML=patch.html}}
`

func renderInteractiveRuntimePage(title, fragment, token string) string {
	return renderInteractiveRuntimePageRevision(title, fragment, token, "")
}

func renderInteractiveRuntimePageRevision(title, fragment, token, revision string) string {
	page := RenderInteractivePage(title, fragment)
	page = strings.Replace(page, `</head>`, `<meta name="md0-runtime-token" content="`+html.EscapeString(token)+`"><meta name="md0-source-revision" content="`+html.EscapeString(revision)+`"><style>`+runtimeStatusCSS+`</style></head>`, 1)
	controls := `<div class="md0-viewer-controls"><button id="md0-settings-toggle" class="md0-settings-toggle" type="button" aria-expanded="false" aria-controls="md0-settings-panel" title="Viewer settings">Aa</button><section id="md0-settings-panel" class="md0-settings-panel" aria-label="Viewer settings" hidden><div class="md0-settings-head"><strong>Viewer</strong><button id="md0-settings-close" class="md0-settings-close" type="button" aria-label="Close settings">×</button></div><label class="md0-preference"><span>Theme</span><select data-md0-preference="theme"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label class="md0-preference"><span>Typography</span><select data-md0-preference="font"><option value="serif">Serif</option><option value="sans">Sans</option><option value="mono">Mono</option></select></label><label class="md0-preference"><span>Density</span><select data-md0-preference="density"><option value="compact">Compact</option><option value="comfortable">Comfortable</option></select></label><label class="md0-preference"><span>Text size</span><select data-md0-preference="textSize"><option value="small">Small</option><option value="default">Default</option><option value="large">Large</option></select></label><label class="md0-preference"><span>Page width</span><select data-md0-preference="width"><option value="narrow">Narrow</option><option value="normal">Normal</option><option value="wide">Wide</option></select></label><div class="md0-settings-separator"></div><div class="md0-settings-actions"><button id="md0-export-snapshot" type="button">Export snapshot</button><button id="md0-export-markdown" type="button">Save values to Markdown</button><button id="md0-settings-reset" class="md0-settings-reset" type="button">Reset viewer settings</button></div></section></div>`
	page = strings.Replace(page, `<body>`, `<body>`+controls+`<aside id="md0-status" class="md0-status" role="status" aria-live="polite" hidden></aside>`, 1)
	page = strings.Replace(page, `</body>`, `<script>`+runtimeStatusJS+`</script></body>`, 1)
	return page
}
